### PR TITLE
[WIP] Patch version

### PR DESCRIPTION
**Pull request by bryanwweber**
Set the version in the meta.yaml file using the Jinja template syntax. To apply this version to the build, we have to patch SConstruct to allow setting the build version from cantera.conf. This is unfortunately somewhat fragile because any changes in SConstruct may invalidate the patch and cause a failure. It also means that the version has to be changed in two places in the repository for a version bump, once in meta.yaml, the other in the deleted line in the patch.

Also add some Python module testing.

The CI is failing because there's an error in conda build when multiple Python versions are specified. I can run a single build locally no problem.

### CODE REVIEW

**Comment by speth** [comment]
Do we just want to revert cantera/cantera@5b483a8c22cc23 and save ourselves some trouble?

**Comment by bryanwweber** [comment]
I'm not sure... I don't like that this is the solution that we have to use, because the version shouldn't be configurable by the end user. In that sense, I would prefer to keep the change in the patch so other people don't try to use the variable. However, it is annoying that the patch is so fragile.

I filed an issue about conda build failing: https://github.com/conda/conda-build/issues/1316

Is there any reason to use Miniconda 2? Or, why do we use Miniconda 3 for Linux x86 only?

Should there be an appveyor.yaml file in the repo?

**Comment by bryanwweber** [comment]
My attempt to get the upload to only run on the master branch is broken, I need to fix a syntax error. I will test locally to fix it then push a fix when available.

**Comment by speth** [comment]
Instead of conda-build-all:
```
conda build cantera --python=2.7 --numpy=1.11
conda build cantera --python=3.4 --numpy=1.11
conda build cantera --python=3.5 --numpy=1.11
```
Is less likely to break when someone decides to change the method for doing this yet again.

**Comment by speth** [comment]
I tried adding the `appveyor.yml` file to the repository, instead of relying on the web interface for configuring it. It doesn't work, and I don't understand why.

**Comment by bryanwweber** [comment]
I'd suggest we look at how conda-forge manages appveyor to help develop the appveyor.yml file. https://github.com/conda-forge/conda-build-all-feedstock/blob/master/appveyor.yml

The reason the build is failing appears to be missing setting some environment variables in appveyor.yml. I think it would be great if we could set up an organization for Cantera at AppVeyor: https://www.appveyor.com/docs/team-setup Since the original is under your account, @speth I think you have to create the team.

The reason the `activate` scripts don't work is because Appveyor uses PowerShell.

**Comment by speth** [comment]
Moving the discussion of Appveyor problems to #3.

**Comment by bryanwweber** [comment]
I sent a PR for a regex function to get data from a file in the source repository: conda/conda-build#1443 Let's see where that goes. Local testing shows that it works great!

**Comment by bryanwweber** [comment]
New conda build is released including the regex function. Hopefully I'll add this over the weekend and close up this PR.

**Comment by bryanwweber** [comment]
Collected into #5

**Pull request closed without merging**
