### PR TITLE
Try conda 3 again

### PR DESCRIPTION
**Pull request by bryanwweber**
Right, so we're going to try to take advantage of conda-build 3 features again. Problems here from my testing today on macOS:

- (If conda_build_config.yaml is set so only one version of Python and numpy are built) The tests don't run, complaining `Undefined Jinja2 variables remain (['group', 'group']).  Please enable source downloading and try again.` Based on some research, I think this is a spurious error message. If I try to test the built package directly with `conda build --test path/to/package.tar.bz2`, I get a dependency unsatisfiable answer, and the hash that conda is looking for is different than the built package (not sure why)
- (If all the intended Pythons and NumPys are enabled in conda_build_config.yaml) Using the `print_outputs` function from https://www.anaconda.com/blog/developer-blog/package-better-conda-build-3/?lang=en-us shows only 4 packages built (one for each version of Python + `libcantera`), not 10 (3 for each of 3 versions of Python + `libcantera`) as expected.
- I expect similar problems on Linux
- Windows... no idea. Let's see how Appveyor fails 😄

### CODE REVIEW

**Comment by bryanwweber** [comment]
I guess I should explain the idea here... I'm trying to split the build such that we can build the core library once, and then package the Python libraries from that single build of the core library. (I guess twice, once for x64, once for x86) This should enable us to get rid of that huge build matrix, and ideally, help the builds go faster, since the longest step (perhaps other than testing) is to build the core library. Once we get this working, extending to provide conda packages for Matlab **should** be fairly easy.

**Comment by bryanwweber** [comment]
Two other reasons for these changes:
1. Use the newer Anaconda packaged compilers, hopefully to minimize compatibility problems
2. Update to the newer syntax to pin package versions

And two more reasons for this PR:
1. For anyone interested in the packaging GSoC project, this is a decent start at that
2. I'm hoping I can get enough information to send a bug report/help request to Anaconda, and having the public build logs would be very helpful in that

Sorry for all the updates, it's been a while since I looked at this, trying to get all of it back in my head!

**Comment by speth** [comment]
So, while in principle building a single shared library and then linking to that from Python modules for different Python versions makes sense, I'm not sure it's worth the effort. One big problem is that we don't actually provide "external" symbols for the C++ library functions, which is required on some operating systems (definitely Windows, I think also MacOS). I looked into doing this at one point, but it's a huge rabbit hole, because you have to declare these symbols not only for your own classes / methods, but for any templated types that those methods return or take as arguments.

**Comment by speth** [comment]
Or wait, is this just re-running SCons in the same source directory, just changing the value of `python3_cmd`  and/or `python2_cmd`, and relying on the fact that SCons won't rebuild the whole thing? In which case, it's generating each of the Python modules from the static cantera library, which should be fine.

**Comment by bryanwweber** [comment]
Yes, the second one. Conda build says that it cleans out the working directory after each packaging step, so ideally, it will reset to the state just after it builds the library, and we can just run the `scons build python*_cmd=...` again.

**Comment by ischg** [comment]
Sounds like an excellent idea.

**Comment by bryanwweber** [comment]
Superseded by #19

**Pull request closed without merging**
