### PR TITLE
Update 23 branch

### PR DESCRIPTION
**Pull request by bryanwweber**
This branch update the versions of conda packages and the Numpy package

### CODE REVIEW

**Comment by speth** [comment]
For the 2.3 branch, does it make sense to continue supporting Numpy 1.11, but also add build for Numpy 1.12? I know this roughly doubles the number of builds, but I'm somewhat concerned about forcing people to upgrade Numpy, and only supporting the latest version might cause irritating conflicts with other Numpy-dependent packages that have not been updated yet.

**Comment by bryanwweber** [comment]
I figured since the 1.11 builds were already built, these would simply add to those. I guess if we have a 2.3.1 release, it would be useful to just build for everything in one shot. I'll change that here.

**Comment by speth** [comment]
Right, the prospect of there being a 2.3.1 is exactly what I was thinking of.

**Comment by bryanwweber** [comment]
If no other comments, I think this is good to merge

**Pull request merged**
